### ISSUE TITLE
what is ADMIN command prompt / powershell

### ISSUE THREAD

**Issue by Tirupatibalaji-Dev** [PHANTOM-14/Snowflake-bot#1]
it have specific name. learn basics of pc and update in README.md

**Comment by Sanchit-codes** [comment]
The name varies of all OS well I don't think you know what is terminal

**Comment by Tirupatibalaji-Dev** [comment]
then don't write readme.me if you cant

**Comment by Sanchit-codes** [comment]
Check what you wrote and teaching me get a new brain kid.

**Comment by Tirupatibalaji-Dev** [comment]
Uff you are total new GitHub player. Please learn something from GitHub
docs and YouTube. GitHub

**Comment by Tirupatibalaji-Dev** [comment]
Ohh I think you are kid.
Baby learn something and then come in thins zone. After making 1-2 bots
anyone dosen't become pro on GitHub. It need to survive.

**Comment by Sanchit-codes** [comment]
Wait I think I am kid and I wrote readme.md to readme.me and I also don't know what is terminal plus what is meant by player get english classes nerd

**Comment by Tirupatibalaji-Dev** [comment]
kid go to school and learn in school.
after 10th grade come in development field

**Comment by Sanchit-codes** [comment]
That is enough come in discord
