### ISSUE TITLE
Snowflake Review:

### ISSUE THREAD

**Issue by KevinSiddhpura** [PHANTOM-14/Snowflake-bot#3]
Has clean UI, Easy to navigate through, Keep it up Dev!

**Comment by Sanchit-codes** [comment]
Ahem I stopped managing it lol 
Learning something new

**Comment by JagritThukral** [comment]
Now continued by fork made by me

**Comment by JagritThukral** [comment]
`close this issue `

**Comment by TheKaushikGoswami** [comment]
Thank You Very Much! <3
